"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

# Wait 10ms to check files under the current directory
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = false

# Prompt with no lang versions
format = """ $character$directory$git_branch$git_status[âœ—](bold yellow) """

# Prompt with lang versions
# format = """$character$directory$git_branch$git_status$c$cpp$elixir$elm$golang$java$python$ruby$rust$nodejs$bun$docker_context$package$localip[âœ—](bold red) """

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Make prompt single line
[line_break]
disabled = true

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[package]
symbol = "ó°— "

[localip]
disabled = true
ssh_only = false
format = 'ó°©Ÿ [$localipv4](bold red) '

[sudo]
#style = "bold green"
#symbol = "ğŸ’» "
#disabled = false

[username]
disabled = true
#style_user = "green bold"
#style_root = "red bold"
#format = "[$user]($style) "
#show_always = true

[hostname]
disabled = true
#ssh_only = false
#format = 'on [$hostname](bold yellow) '
#trim_at = "."

[directory]
read_only = " ó°¯„"
truncation_length = 4
truncate_to_repo = true
style = "bold blue"

# Substitute directory names with icons
# [directory.substitutions]
# 'Documents' = 'ó°ˆ™'
# 'Downloads' = 'ï€™ '
# 'Music' = 'ï€ '
# 'Pictures' = 'ï€¾ '

[cmd_duration]
disabled = true
#min_time = 4
#show_milliseconds = false
#style = "bold italic red"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "bold #f5bde6"
format = "[$all_status$ahead_behind]($style)[\\)](bold mauve) "

[aws]
symbol = "î­ "

[conda]
symbol = "î˜• "

[dart]
symbol = "î™Œ "

[docker_context]
symbol = "î° "
format = "  [$symbol$context]($style) "
style = "bold blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[c]
# symbol = "î˜ "
commands = [['gcc-15', '--version']]
format = "[gcc:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[cpp]
disabled = false
commands = [['g++-15', '--version']]
format = "[g++:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
# detect_extensions = ["cpp", "cxx", "cc", "c++", "hpp", "hxx", "h++", "hh"]

[elixir]
# symbol = "î˜­ "
format = "[elixir:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[elm]
# symbol = "î˜¬ "
format = "[elm:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[git_branch]
# symbol = " ó°˜¬ "
style = "bold pink"
format = "[git:\\(](bold mauve)[$branch]($style)"

[golang]
# symbol = "î˜§ "
format = "[golang:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[hg_branch]
symbol = "ó°˜¬ "

[java]
# symbol = "îœ¸ "
format = "[java:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ó°› "

[nim]
symbol = "î™· "

[nix_shell]
symbol = "ó±„… "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
# symbol = "î˜† "
#pyenv_version_name = true
format = "[py:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = "î˜… "
format = "[ruby:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[rust]
symbol = "î¨ "
format = "[rust:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "ï„  "

[swift]
symbol = "î• "

[nodejs]
format = "[node:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
detect_files = ["package.json", ".node-version", "yarn.lock", "pnpm-lock.yaml"]
detect_folders = ["node_modules"]

[bun]
format = "[bun:\\(](bold #91d7e3)[$version](bold #f0c6c6)[\\)](bold #91d7e3) "
