"$schema" = 'https://starship.rs/config-schema.json'

# palette = "catppuccin_mocha"

# Wait 10ms to check files under the current directory
scan_timeout = 10

add_newline = false

# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

[line_break]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
# success_symbol = '[❯](bold green)'
# error_symbol = '[❯](bold red)'
# success_symbol = "[\\$](green)"
# error_symbol = "[\\$](red)"

[package]
disabled = true
symbol = "󰏗 "

[localip]
disabled = true
ssh_only = false
format = '󰩟 [$localipv4](bold red) '

[username]
disabled = true
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
show_always = true

[hostname]
disabled = true
ssh_only = false
format = 'on [$hostname](bold yellow) '
trim_at = "."

[directory]
read_only = " 󰯄"
truncation_length = 4
truncate_to_repo = true
style = "blue"

[cmd_duration]
disabled = true
min_time = 4
show_milliseconds = false
style = "bold italic red"


[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
style = "bold blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[c]
symbol = ""
commands = [['gcc-15', '--version']]
format = "via [$symbol](bold yellow) [$version](yellow) "

[cpp]
symbol = ""
commands = [['g++-15', '--version']]
format = "via [$symbol](yellow) [$version](yellow) "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = "󰘬 "
format = "on [$symbol](bold purple)[$branch(:$remote_branch)](purple) "

[git_metrics]
disabled = true

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[golang]
symbol = ""
format = "via [$symbol](bold yellow) [$version](yellow) "

[hg_branch]
symbol = "󰘬 "

[java]
symbol = " "
style = "yellow"

[julia]
symbol = " "
style = "yellow"

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "yellow"
pyenv_version_name = false
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
format = "via [$symbol](bold yellow)[$version]($style)[(\\($virtualenv\\))]($style) "

[ruby]
symbol = " "

[rust]
symbol = " "
format = "via [$symbol](bold yellow)[$version](yellow) "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = " "

[nodejs]
symbol = " "
format = "via [$symbol](bold yellow)[$version](yellow) "
detect_files = ["package.json", ".node-version", "yarn.lock", "pnpm-lock.yaml"]
detect_folders = ["node_modules"]
